### ISSUE TITLE
index instead of genes in plotVolcano or topTable 

### ISSUE THREAD

**Issue by michalmark** [GabrielHoffman/dreamlet_analysis#1]
Hi, 

I keep getting the index number instead of genes name (see fig below) after applying the aggregateToPseudoBulk and processAssays functions with genes names in both. What can be the problem? 
![Volcano_notworking](https://user-images.githubusercontent.com/103484145/236895678-a0af05c5-3c20-4932-88e4-68a82f760f13.png)

Thanks!

**Comment by GabrielHoffman** [comment]
Hi Michal, 
It's likely an issue with the naming of genes in the input data, or a bug on my end.  Can you share a minimal reproducible example so I can investigate further.

Gabriel

**Comment by michalmark** [comment]
Hi Gabriel, 

I found my issue in my input data and corrected it. 
There is no bug on your end. 

Thanks for the fast reply:)
Michal
