### ISSUE TITLE
lfcShrink for the Dreamlet DE output 

### ISSUE THREAD

**Issue by michalmark** [GabrielHoffman/dreamlet_analysis#2]
Hi Gabriel, 

Thanks for the great package and  the high responsiveness. 

I was wondering if there is a way to apply the lfcShrink (from the DESeq2) for the DE Dreamlet results? 

Thanks again, 

Michal

**Comment by GabrielHoffman** [comment]
In short, no.  There are two widely used approaches and software for differential expression analyses.

1) DESeq2 shrinks the effect distribution estimates.
2) limma's eBayes() puts a prior on the residual variance to shrinkage the estimate of \sig^2_e for each gene.  These shrunken values are then used to create "moderated t-statistics".  So the effect sizes are not shrunk.

dream / dreamlet is inspired by limma, so its doesn't shrink.
