### ISSUE TITLE
Labeling user-selected genes with plotVolcano 

### ISSUE THREAD

**Issue by jenellewallace** [GabrielHoffman/dreamlet_analysis#4]
HI, thanks for such a great package - it's working really well for me. I'm wondering if there is a way to label the points corresponding to a predefined list of genes with plotVolcano - I see that the resulting object is made with ggplot2 and geom_text_repel but haven't been able to figure out how to modify which genes are labeled. Thanks for any guidance!

**Comment by GabrielHoffman** [comment]
Unfortunately, there is no a good way of doing this with the current implementation.  You would have to look at the internals of the function and write some custom code

**Comment by jenellewallace** [comment]
Thanks, I appreciate the quick response. I'd be happy to write some custom code - would you be able to share the source code for the function? Sorry if I'm missing where it is but I only see the analysis code posted right now

**Comment by GabrielHoffman** [comment]
I guess I didn't paste the link.  Here: https://github.com/DiseaseNeuroGenomics/dreamlet/blob/c637503ca22cde2112a503edfe0a4382255a97a9/R/plotVolcano.R#L130

**Comment by jenellewallace** [comment]
Thank you!!
