### ISSUE TITLE
model formulas for processAssays, variancePartition, and dreamlet

### ISSUE THREAD

**Issue by jenellewallace** [GabrielHoffman/dreamlet_analysis#5]
Hi, this is more of a theoretical question but I'm hoping you could clarify. Does it matter if the model formula used for processAssays is the same as the variancePartition formula vs. the dreamlet formula for differential expression? I understand that there are limitations on the variancePartition formula (all random variables or random for categorical/fixed for continuous) and of course the formula for the dreamlet differential expression model should take into account the experimental design for assigning random vs fixed effects but I'm unclear on  which version should match the processAssays step. In your worked examples, I see examples both ways, so I'm wondering if there's a guideline here or whether it matters and why. Thanks so much for your advice.

**Comment by GabrielHoffman** [comment]
There are 3 main uses of regression formulas here 1) `processAssays()` for voom, 2) variance partitioning and 3) differential analysis with `dreamlet()`.  Beyond the slightly different formula requirements for 2 and 3, the formula for 1 should be close to the others but doesn't need to be identical.  voom analysis uses the residuals from the regression, so it depends on including the major variables that explain variance but is robust to dropping minor variables.  Differential expression analysis often focuses on minor effects that don't explain much variance.  There is no need to rerun `processAssays()` with these minor variables

Gabriel

**Comment by jenellewallace** [comment]
Thanks for the explanation! I understand that all of the major variables that explain the most variance should be included in the processAssays formula for voom. But in the case where there's a categorical variable that I need to be a fixed effect for the dreamlet formula (and would be random effect for variancepartition), does it matter if it's fixed or random in the processAssays formula for voom? Thanks for your responsiveness, really appreciate it.

**Comment by GabrielHoffman** [comment]
In that case, the difference between fixed and random only matters when there are a lot of levels in the categorical variable, compared to the sample size.  With something like sex with 2 levels, then fixed and random are almost identical, but fixed is faster.  However, something like Subject ID with many levels should be modeled as a random effect.  For `n` samples, if a variable has > `sqrt(n)` levels, then definitely use a random effect.
